### ISSUE TITLE
Rewrite AST parser to be solc compatible

### ISSUE THREAD

**Issue by 0x19** [txpull/solgo#16]
Right now they are basic, only text. We should change that each by each case as there are so many of them.

**Comment by NixoN2** [comment]
Hello! Is there a way to collaborate on this project? I am looking for a way to migrate my smart contracts static analysis tool from typescript to golang and this project looks promising

**Comment by 0x19** [comment]
> Hello! Is there a way to collaborate on this project? I am looking for a way to migrate my smart contracts static analysis tool from typescript to golang and this project looks promising

Hey man! First of all sorry for not seeing comment. I did not yet expect any involvement from other people into this project.

Of course there is way. I would love some help here as this is literally a nightmare to build but so fun!

Can you please reach me at nevio@inorbit.hr and we can continue from there.

**Comment by 0x19** [comment]
Related to statements, in #35 you can find work I am doing right now to get AST package closer to something that is even remotely useful.

**Comment by 0x19** [comment]
Few important things to say about this upgrade:

- It will be almost sol compatible. I do see some improvements that could be done in the AST output such as applying comments, giving better source information / insight into the lines.
- AST layout will be protocol buffers based as idea is to be able stream AST from `unpack` service or any other and provide a strict layout that services will need to follow.

**Comment by 0x19** [comment]
Just a sidenote, this is a monster...

**Comment by 0x19** [comment]
First batch completed. New tickets will be created for remaining workload.
